function lorum_ipsum(){
	var text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eleifend ultrices velit, at cursus ipsum accumsan sit amet. Suspendisse posuere sapien vel urna facilisis vehicula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam nunc turpis, cursus sed euismod nec, rutrum ut lectus. Nunc non nisl urna. Aliquam posuere semper mattis. Suspendisse dolor ante, laoreet ac mattis eget, dictum vitae lectus. Integer tincidunt felis sed felis ornare mattis. Aliquam eu eros tristique, feugiat dolor non, consectetur urna.\
	\
	Suspendisse dui leo, porta vitae vestibulum in, auctor vitae quam. Duis ornare consectetur justo, sit amet feugiat velit tempus at. Etiam id nibh a dui lobortis faucibus. Quisque lacus elit, dictum ut leo vitae, adipiscing cursus neque. Maecenas aliquet sem sit amet mauris ultrices, vitae interdum orci rhoncus. Vivamus pharetra ante ut nulla interdum eleifend. Praesent interdum, nulla sed viverra ullamcorper, velit nunc ultricies orci, cursus imperdiet mi enim ut augue. Morbi vehicula sem semper purus imperdiet aliquet. Nam metus odio, scelerisque pulvinar lacinia eu, condimentum et metus. Morbi volutpat rhoncus euismod. Vestibulum vestibulum nibh sit amet sollicitudin cursus.\
	\
	Donec tellus ante, cursus nec elit ut, egestas rhoncus dui. Cras sed neque dolor. Vivamus ut mi tristique, posuere nisi dictum, malesuada turpis. Fusce fermentum a elit quis porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque enim nulla, accumsan eu nisl vel, convallis feugiat leo. Suspendisse semper orci sed lorem tempus, eget egestas arcu varius. Curabitur at accumsan turpis, vitae ultricies orci. Nam id nibh velit. Nam imperdiet convallis gravida. Donec ac sem eu risus eleifend euismod. Etiam eros elit, aliquam a risus eu, lacinia mattis nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean ipsum lectus, consequat in est et, elementum consequat mauris. Pellentesque suscipit augue vel ultricies scelerisque.\
	\
	Phasellus rutrum tellus mauris, ac rutrum nunc condimentum vel. Proin nec euismod neque. Pellentesque in porttitor leo. Phasellus eget nisl pharetra, ultrices lacus quis, tempus neque. Aliquam ullamcorper eu nibh a tincidunt. Curabitur pharetra sapien metus, non vulputate lorem consectetur a. Vivamus elit nisi, sodales non sagittis in, molestie eu libero. Vestibulum malesuada ante eu nisl dignissim, cursus porta sem porta. Aliquam a dui egestas, feugiat justo rutrum, malesuada nunc. Aenean commodo eros lacus. Maecenas malesuada tincidunt faucibus. Vestibulum sed massa ut libero ullamcorper bibendum. Nam et quam nec massa pulvinar fringilla.\
	\
	Nullam malesuada, sem at egestas sodales, quam lorem vehicula ante, et pretium turpis turpis et massa. Nulla eget fermentum orci. Vestibulum dapibus leo nibh, eu auctor augue commodo quis. Nulla sed lorem eu orci iaculis pretium sed ac magna. Phasellus eu mollis lectus, et hendrerit magna. Phasellus fringilla, augue sed consectetur scelerisque, ante leo gravida nisi, nec gravida neque nulla vitae sapien. Duis dictum tortor sit amet nunc tempus, vel accumsan nibh placerat. Nunc porta libero velit, elementum euismod risus venenatis condimentum. Sed vitae purus et odio porttitor sodales sed sed augue. Donec imperdiet, magna at vehicula pretium, magna purus venenatis odio, ac malesuada tellus dolor eu nulla. Donec at mi in augue mattis tristique vel quis nulla. Proin imperdiet, justo quis pellentesque luctus, ligula dolor accumsan leo, at fringilla nisl odio eu dolor. Aliquam odio massa, malesuada at porta nec, aliquam ac augue. Aliquam non tortor laoreet, pellentesque tellus vehicula, molestie orci. Proin placerat arcu vitae nisi bibendum, sit amet consectetur magna congue. Ut tempor, lectus commodo congue commodo, metus sapien posuere odio, eget sollicitudin risus nibh in enim.\
	\
	Etiam neque dui, blandit in rutrum non, scelerisque sit amet lacus. Nunc tincidunt ut sem sed consectetur. Fusce vitae gravida mi, eu vulputate felis. Aenean dolor diam, elementum sit amet aliquam ut, lacinia ac orci. Phasellus ligula nisl, facilisis ut tellus sit amet, fringilla ullamcorper libero. Donec eleifend risus hendrerit porta viverra. Proin eget libero vel elit malesuada sagittis a ut elit. Proin dapibus metus id quam venenatis rutrum eu sed leo. Aliquam vitae facilisis purus, quis tincidunt erat. Etiam eleifend vitae nisi in semper. Etiam et rutrum neque.\
	\
	Integer sed placerat nulla. Nam diam metus, semper et purus a, euismod ultricies magna. Sed tempor nibh ut nulla accumsan scelerisque. Aliquam tempus mauris ac mi egestas faucibus. Integer at nisi a ante mollis convallis non at felis. Fusce non dictum mauris. Suspendisse dictum tincidunt elementum. Cras lobortis, lectus ac porta tincidunt, risus est vestibulum ipsum, ut dictum nisl augue vitae sem. Sed tincidunt quam vel leo iaculis faucibus. Aenean non arcu hendrerit, aliquet enim at, vulputate sapien. Aenean egestas dolor sit amet imperdiet feugiat. Aenean et mauris mi.\
	\
	Etiam eu lectus nibh. Maecenas eget consequat nisl, ut consequat nisi. Pellentesque at massa varius ante tincidunt viverra. Pellentesque tempor risus sed vehicula auctor. Sed ligula lacus, vehicula ac feugiat id, vehicula ac augue. Ut viverra arcu et cursus lacinia. Nunc quis dolor venenatis urna facilisis sollicitudin at ut libero. Maecenas condimentum lacus at quam ultricies sagittis. Nunc ante mauris, feugiat non erat et, consequat convallis dui. Nullam a porttitor sem. Fusce id imperdiet quam. Nulla ultrices tempus leo quis pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\
	\
	Etiam dignissim metus nec tincidunt porttitor. Aliquam mollis porta posuere. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce vehicula mollis odio et ullamcorper. Donec risus dui, condimentum a dui sit amet, condimentum vulputate sem. Proin massa orci, feugiat non ligula vel, mattis vulputate nisi. Morbi a velit quam. Morbi id ultrices magna. Sed porttitor leo eu venenatis vulputate. Proin sit amet diam sit amet quam malesuada dignissim. Vivamus vitae odio at urna malesuada cursus sed at massa. Phasellus porttitor ut sem id molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam sed nulla accumsan lorem vestibulum dignissim ut et arcu. Fusce vulputate vitae enim ultrices bibendum. Nulla augue lectus, hendrerit non erat et, condimentum luctus justo.\
	\
	Quisque magna est, tempus vel leo et, congue consectetur massa. Donec neque tellus, auctor ut faucibus vitae, tempus semper magna. Nunc ultricies interdum ipsum, id posuere nunc elementum nec. Morbi molestie et nisi vel mattis. Cras.";
}